### ISSUE TITLE
DB engine, Db and filtering

### ISSUE THREAD

**Issue by CarolineMorton** [maxwellflitton/imperial-coronavirus-data-node#5]
Hi Maxwell, 

I need to find a way to filter the database by username and email so that the registration form does not allow multiple users to be created on the same username / email. We are using a custom DB engine, and there is no filter or query attribute. Do you know how to add this in? I feel it must be part of the base (from whcih we are subclassed) but I can't be sure. 

Cheers
Caroline

**Comment by maxwellflitton** [comment]
```username``` and ```email``` are unique constraints in the database so this will not be an issue
